trigger:
- main   # or your branch name

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # use your .NET version

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/GiftofGivers web.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Your-Azure-Service-Connection'
    appName: 'GiftofGivers-Web'  # exact App Service name
    package: '$(Build.ArtifactStagingDirectory)/**'
